### ISSUE TITLE
`Vuetify` tables for core views

### ISSUE THREAD

**Issue by diogosmac** [Marantesss/feup-sinf#15]
### Tasks
- [X] Structure of table
- [x] Passing table name as argument from outside
- [x] Passing table data as argument from outside

**PS:** Contains code that can be used for #8
