### ISSUE TITLE
Overview page :art:

### ISSUE THREAD

**Issue by Marantesss** [Marantesss/feup-sinf#8]
**Tasks:**
- [X] Fix size for the data containers (2x2 layout)
- [X] Fix CSS for tables
- [x] Fix size of charts to fix desired container size
